onerror {resume}
radix define fixed#8#decimal#signed -fixed -fraction 8 -signed -base signed -precision 6
radix define fixed#8#decimal -fixed -fraction 8 -base signed -precision 6
quietly virtual function -install /fft_test/DUT/fft_samples -env /fft_test/#INITIAL#17 { &{/fft_test/DUT/fft_samples/register[0][31], /fft_test/DUT/fft_samples/register[0][30], /fft_test/DUT/fft_samples/register[0][29], /fft_test/DUT/fft_samples/register[0][28], /fft_test/DUT/fft_samples/register[0][27], /fft_test/DUT/fft_samples/register[0][26], /fft_test/DUT/fft_samples/register[0][25], /fft_test/DUT/fft_samples/register[0][24], /fft_test/DUT/fft_samples/register[0][23], /fft_test/DUT/fft_samples/register[0][22], /fft_test/DUT/fft_samples/register[0][21], /fft_test/DUT/fft_samples/register[0][20], /fft_test/DUT/fft_samples/register[0][19], /fft_test/DUT/fft_samples/register[0][18], /fft_test/DUT/fft_samples/register[0][17], /fft_test/DUT/fft_samples/register[0][16] }} real_first
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x0[31], /fft_test/x0[30], /fft_test/x0[29], /fft_test/x0[28], /fft_test/x0[27], /fft_test/x0[26], /fft_test/x0[25], /fft_test/x0[24], /fft_test/x0[23], /fft_test/x0[22], /fft_test/x0[21], /fft_test/x0[20], /fft_test/x0[19], /fft_test/x0[18], /fft_test/x0[17], /fft_test/x0[16] }} x0_real
quietly virtual function -install /fft_test/DUT/fft_samples -env /fft_test/#INITIAL#17 { &{/fft_test/DUT/fft_samples/register[1][31], /fft_test/DUT/fft_samples/register[1][30], /fft_test/DUT/fft_samples/register[1][29], /fft_test/DUT/fft_samples/register[1][28], /fft_test/DUT/fft_samples/register[1][27], /fft_test/DUT/fft_samples/register[1][26], /fft_test/DUT/fft_samples/register[1][25], /fft_test/DUT/fft_samples/register[1][24], /fft_test/DUT/fft_samples/register[1][23], /fft_test/DUT/fft_samples/register[1][22], /fft_test/DUT/fft_samples/register[1][21], /fft_test/DUT/fft_samples/register[1][20], /fft_test/DUT/fft_samples/register[1][19], /fft_test/DUT/fft_samples/register[1][18], /fft_test/DUT/fft_samples/register[1][17], /fft_test/DUT/fft_samples/register[1][16] }} real_2
quietly virtual function -install /fft_test/DUT/fft_samples -env /fft_test/#INITIAL#17 { &{/fft_test/DUT/fft_samples/register[2][31], /fft_test/DUT/fft_samples/register[2][30], /fft_test/DUT/fft_samples/register[2][29], /fft_test/DUT/fft_samples/register[2][28], /fft_test/DUT/fft_samples/register[2][27], /fft_test/DUT/fft_samples/register[2][26], /fft_test/DUT/fft_samples/register[2][25], /fft_test/DUT/fft_samples/register[2][24], /fft_test/DUT/fft_samples/register[2][23], /fft_test/DUT/fft_samples/register[2][22], /fft_test/DUT/fft_samples/register[2][21], /fft_test/DUT/fft_samples/register[2][20], /fft_test/DUT/fft_samples/register[2][19], /fft_test/DUT/fft_samples/register[2][18], /fft_test/DUT/fft_samples/register[2][17], /fft_test/DUT/fft_samples/register[2][16] }} real_3
quietly virtual signal -install /fft_test { /fft_test/y0[31:16]} y_0_real
quietly virtual signal -install /fft_test { /fft_test/y1[31:16]} y_1_real
quietly virtual signal -install /fft_test { /fft_test/y1[15:0]} y_1_imag
quietly virtual signal -install /fft_test { /fft_test/y2[31:16]} y2_real
quietly virtual signal -install /fft_test { /fft_test/y2[15:0]} y_2_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x0[15], /fft_test/x0[14], /fft_test/x0[13], /fft_test/x0[12], /fft_test/x0[11], /fft_test/x0[10], /fft_test/x0[9], /fft_test/x0[8], /fft_test/x0[7], /fft_test/x0[6], /fft_test/x0[5], /fft_test/x0[4], /fft_test/x0[3], /fft_test/x0[2], /fft_test/x0[1], /fft_test/x0[0] }} x0_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x1[31], /fft_test/x1[30], /fft_test/x1[29], /fft_test/x1[28], /fft_test/x1[27], /fft_test/x1[26], /fft_test/x1[25], /fft_test/x1[24], /fft_test/x1[23], /fft_test/x1[22], /fft_test/x1[21], /fft_test/x1[20], /fft_test/x1[19], /fft_test/x1[18], /fft_test/x1[17], /fft_test/x1[16] }} x1_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x1[15], /fft_test/x1[14], /fft_test/x1[13], /fft_test/x1[12], /fft_test/x1[11], /fft_test/x1[10], /fft_test/x1[9], /fft_test/x1[8], /fft_test/x1[7], /fft_test/x1[6], /fft_test/x1[5], /fft_test/x1[4], /fft_test/x1[3], /fft_test/x1[2], /fft_test/x1[1], /fft_test/x1[0] }} x1_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x3[31], /fft_test/x3[30], /fft_test/x3[29], /fft_test/x3[28], /fft_test/x3[27], /fft_test/x3[26], /fft_test/x3[25], /fft_test/x3[24], /fft_test/x3[23], /fft_test/x3[22], /fft_test/x3[21], /fft_test/x3[20], /fft_test/x3[19], /fft_test/x3[18], /fft_test/x3[17], /fft_test/x3[16] }} x3_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x3[15], /fft_test/x3[14], /fft_test/x3[13], /fft_test/x3[12], /fft_test/x3[11], /fft_test/x3[10], /fft_test/x3[9], /fft_test/x3[8], /fft_test/x3[7], /fft_test/x3[6], /fft_test/x3[5], /fft_test/x3[4], /fft_test/x3[3], /fft_test/x3[2], /fft_test/x3[1], /fft_test/x3[0] }} x3_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x4[31], /fft_test/x4[30], /fft_test/x4[29], /fft_test/x4[28], /fft_test/x4[27], /fft_test/x4[26], /fft_test/x4[25], /fft_test/x4[24], /fft_test/x4[23], /fft_test/x4[22], /fft_test/x4[21], /fft_test/x4[20], /fft_test/x4[19], /fft_test/x4[18], /fft_test/x4[17], /fft_test/x4[16] }} x4_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x4[15], /fft_test/x4[14], /fft_test/x4[13], /fft_test/x4[12], /fft_test/x4[11], /fft_test/x4[10], /fft_test/x4[9], /fft_test/x4[8], /fft_test/x4[7], /fft_test/x4[6], /fft_test/x4[5], /fft_test/x4[4], /fft_test/x4[3], /fft_test/x4[2], /fft_test/x4[1], /fft_test/x4[0] }} x4_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x5[31], /fft_test/x5[30], /fft_test/x5[29], /fft_test/x5[28], /fft_test/x5[27], /fft_test/x5[26], /fft_test/x5[25], /fft_test/x5[24], /fft_test/x5[23], /fft_test/x5[22], /fft_test/x5[21], /fft_test/x5[20], /fft_test/x5[19], /fft_test/x5[18], /fft_test/x5[17], /fft_test/x5[16] }} x5_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x5[15], /fft_test/x5[14], /fft_test/x5[13], /fft_test/x5[12], /fft_test/x5[11], /fft_test/x5[10], /fft_test/x5[9], /fft_test/x5[8], /fft_test/x5[7], /fft_test/x5[6], /fft_test/x5[5], /fft_test/x5[4], /fft_test/x5[3], /fft_test/x5[2], /fft_test/x5[1], /fft_test/x5[0] }} x5_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x6[31], /fft_test/x6[30], /fft_test/x6[29], /fft_test/x6[28], /fft_test/x6[27], /fft_test/x6[26], /fft_test/x6[25], /fft_test/x6[24], /fft_test/x6[23], /fft_test/x6[22], /fft_test/x6[21], /fft_test/x6[20], /fft_test/x6[19], /fft_test/x6[18], /fft_test/x6[17], /fft_test/x6[16] }} x6_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x6[15], /fft_test/x6[14], /fft_test/x6[13], /fft_test/x6[12], /fft_test/x6[11], /fft_test/x6[10], /fft_test/x6[9], /fft_test/x6[8], /fft_test/x6[7], /fft_test/x6[6], /fft_test/x6[5], /fft_test/x6[4], /fft_test/x6[3], /fft_test/x6[2], /fft_test/x6[1], /fft_test/x6[0] }} x6_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x7[31], /fft_test/x7[30], /fft_test/x7[29], /fft_test/x7[28], /fft_test/x7[27], /fft_test/x7[26], /fft_test/x7[25], /fft_test/x7[24], /fft_test/x7[23], /fft_test/x7[22], /fft_test/x7[21], /fft_test/x7[20], /fft_test/x7[19], /fft_test/x7[18], /fft_test/x7[17], /fft_test/x7[16] }} x7_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x7[15], /fft_test/x7[14], /fft_test/x7[13], /fft_test/x7[12], /fft_test/x7[11], /fft_test/x7[10], /fft_test/x7[9], /fft_test/x7[8], /fft_test/x7[7], /fft_test/x7[6], /fft_test/x7[5], /fft_test/x7[4], /fft_test/x7[3], /fft_test/x7[2], /fft_test/x7[1], /fft_test/x7[0] }} x7_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x8[31], /fft_test/x8[30], /fft_test/x8[29], /fft_test/x8[28], /fft_test/x8[27], /fft_test/x8[26], /fft_test/x8[25], /fft_test/x8[24], /fft_test/x8[23], /fft_test/x8[22], /fft_test/x8[21], /fft_test/x8[20], /fft_test/x8[19], /fft_test/x8[18], /fft_test/x8[17], /fft_test/x8[16] }} x8_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x8[15], /fft_test/x8[14], /fft_test/x8[13], /fft_test/x8[12], /fft_test/x8[11], /fft_test/x8[10], /fft_test/x8[9], /fft_test/x8[8], /fft_test/x8[7], /fft_test/x8[6], /fft_test/x8[5], /fft_test/x8[4], /fft_test/x8[3], /fft_test/x8[2], /fft_test/x8[1], /fft_test/x8[0] }} x8_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x9[31], /fft_test/x9[30], /fft_test/x9[29], /fft_test/x9[28], /fft_test/x9[27], /fft_test/x9[26], /fft_test/x9[25], /fft_test/x9[24], /fft_test/x9[23], /fft_test/x9[22], /fft_test/x9[21], /fft_test/x9[20], /fft_test/x9[19], /fft_test/x9[18], /fft_test/x9[17], /fft_test/x9[16] }} x9_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x9[15], /fft_test/x9[14], /fft_test/x9[13], /fft_test/x9[12], /fft_test/x9[11], /fft_test/x9[10], /fft_test/x9[9], /fft_test/x9[8], /fft_test/x9[7], /fft_test/x9[6], /fft_test/x9[5], /fft_test/x9[4], /fft_test/x9[3], /fft_test/x9[2], /fft_test/x9[1], /fft_test/x9[0] }} x9_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x10[31], /fft_test/x10[30], /fft_test/x10[29], /fft_test/x10[28], /fft_test/x10[27], /fft_test/x10[26], /fft_test/x10[25], /fft_test/x10[24], /fft_test/x10[23], /fft_test/x10[22], /fft_test/x10[21], /fft_test/x10[20], /fft_test/x10[19], /fft_test/x10[18], /fft_test/x10[17], /fft_test/x10[16] }} x10_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x10[15], /fft_test/x10[14], /fft_test/x10[13], /fft_test/x10[12], /fft_test/x10[11], /fft_test/x10[10], /fft_test/x10[9], /fft_test/x10[8], /fft_test/x10[7], /fft_test/x10[6], /fft_test/x10[5], /fft_test/x10[4], /fft_test/x10[3], /fft_test/x10[2], /fft_test/x10[1], /fft_test/x10[0] }} x10_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x11[31], /fft_test/x11[30], /fft_test/x11[29], /fft_test/x11[28], /fft_test/x11[27], /fft_test/x11[26], /fft_test/x11[25], /fft_test/x11[24], /fft_test/x11[23], /fft_test/x11[22], /fft_test/x11[21], /fft_test/x11[20], /fft_test/x11[19], /fft_test/x11[18], /fft_test/x11[17], /fft_test/x11[16] }} x11_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x11[15], /fft_test/x11[14], /fft_test/x11[13], /fft_test/x11[12], /fft_test/x11[11], /fft_test/x11[10], /fft_test/x11[9], /fft_test/x11[8], /fft_test/x11[7], /fft_test/x11[6], /fft_test/x11[5], /fft_test/x11[4], /fft_test/x11[3], /fft_test/x11[2], /fft_test/x11[1], /fft_test/x11[0] }} x11_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x12[31], /fft_test/x12[30], /fft_test/x12[29], /fft_test/x12[28], /fft_test/x12[27], /fft_test/x12[26], /fft_test/x12[25], /fft_test/x12[24], /fft_test/x12[23], /fft_test/x12[22], /fft_test/x12[21], /fft_test/x12[20], /fft_test/x12[19], /fft_test/x12[18], /fft_test/x12[17], /fft_test/x12[16] }} x12_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x12[15], /fft_test/x12[14], /fft_test/x12[13], /fft_test/x12[12], /fft_test/x12[11], /fft_test/x12[10], /fft_test/x12[9], /fft_test/x12[8], /fft_test/x12[7], /fft_test/x12[6], /fft_test/x12[5], /fft_test/x12[4], /fft_test/x12[3], /fft_test/x12[2], /fft_test/x12[1], /fft_test/x12[0] }} x12_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x13[31], /fft_test/x13[30], /fft_test/x13[29], /fft_test/x13[28], /fft_test/x13[27], /fft_test/x13[26], /fft_test/x13[25], /fft_test/x13[24], /fft_test/x13[23], /fft_test/x13[22], /fft_test/x13[21], /fft_test/x13[20], /fft_test/x13[19], /fft_test/x13[18], /fft_test/x13[17], /fft_test/x13[16] }} x13_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x13[15], /fft_test/x13[14], /fft_test/x13[13], /fft_test/x13[12], /fft_test/x13[11], /fft_test/x13[10], /fft_test/x13[9], /fft_test/x13[8], /fft_test/x13[7], /fft_test/x13[6], /fft_test/x13[5], /fft_test/x13[4], /fft_test/x13[3], /fft_test/x13[2], /fft_test/x13[1], /fft_test/x13[0] }} x13_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x14[31], /fft_test/x14[30], /fft_test/x14[29], /fft_test/x14[28], /fft_test/x14[27], /fft_test/x14[26], /fft_test/x14[25], /fft_test/x14[24], /fft_test/x14[23], /fft_test/x14[22], /fft_test/x14[21], /fft_test/x14[20], /fft_test/x14[19], /fft_test/x14[18], /fft_test/x14[17], /fft_test/x14[16] }} x14_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x14[15], /fft_test/x14[14], /fft_test/x14[13], /fft_test/x14[12], /fft_test/x14[11], /fft_test/x14[10], /fft_test/x14[9], /fft_test/x14[8], /fft_test/x14[7], /fft_test/x14[6], /fft_test/x14[5], /fft_test/x14[4], /fft_test/x14[3], /fft_test/x14[2], /fft_test/x14[1], /fft_test/x14[0] }} x14_imag
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x15[31], /fft_test/x15[30], /fft_test/x15[29], /fft_test/x15[28], /fft_test/x15[27], /fft_test/x15[26], /fft_test/x15[25], /fft_test/x15[24], /fft_test/x15[23], /fft_test/x15[22], /fft_test/x15[21], /fft_test/x15[20], /fft_test/x15[19], /fft_test/x15[18], /fft_test/x15[17], /fft_test/x15[16] }} x15_real
quietly virtual function -install /fft_test -env /fft_test/#INITIAL#17 { &{/fft_test/x15[15], /fft_test/x15[14], /fft_test/x15[13], /fft_test/x15[12], /fft_test/x15[11], /fft_test/x15[10], /fft_test/x15[9], /fft_test/x15[8], /fft_test/x15[7], /fft_test/x15[6], /fft_test/x15[5], /fft_test/x15[4], /fft_test/x15[3], /fft_test/x15[2], /fft_test/x15[1], /fft_test/x15[0] }} x15_imag
quietly virtual signal -install /fft_test { /fft_test/y0[31:16]} y0_real
quietly virtual signal -install /fft_test { /fft_test/y0[15:0]} y0_imag
quietly virtual signal -install /fft_test { /fft_test/y1[31:16]} y1_real
quietly virtual signal -install /fft_test { /fft_test/y1[15:0]} y1_imag
quietly virtual signal -install /fft_test { /fft_test/y2[15:0]} y2_imag
quietly virtual signal -install /fft_test { /fft_test/y3[31:16]} y3_real
quietly virtual signal -install /fft_test { /fft_test/y3[15:0]} y3_imag
quietly virtual signal -install /fft_test { /fft_test/y4[31:16]} y4_real
quietly virtual signal -install /fft_test { /fft_test/y4[15:0]} y4_imag
quietly virtual signal -install /fft_test { /fft_test/y5[31:16]} y5_real
quietly virtual signal -install /fft_test { /fft_test/y5[15:0]} y5_imag
quietly virtual signal -install /fft_test { /fft_test/y6[31:16]} y6_real
quietly virtual signal -install /fft_test { /fft_test/y6[15:0]} y6_imag
quietly virtual signal -install /fft_test { /fft_test/y7[31:16]} y7_real
quietly virtual signal -install /fft_test { /fft_test/y7[15:0]} y7_imag
quietly virtual signal -install /fft_test { /fft_test/y8[31:16]} y8_real
quietly virtual signal -install /fft_test { /fft_test/y8[15:0]} y8_imag
quietly virtual signal -install /fft_test { /fft_test/y9[31:16]} y9_real
quietly virtual signal -install /fft_test { /fft_test/y9[15:0]} y9_imag
quietly virtual signal -install /fft_test { /fft_test/y10[31:16]} y10_real
quietly virtual signal -install /fft_test { /fft_test/y10[15:0]} y10_imag
quietly virtual signal -install /fft_test { /fft_test/y11[31:16]} y11_real
quietly virtual signal -install /fft_test { /fft_test/y11[15:0]} y11_imag
quietly virtual signal -install /fft_test { /fft_test/y12[31:16]} y12_real
quietly virtual signal -install /fft_test { /fft_test/y12[15:0]} y12_imag
quietly virtual signal -install /fft_test { /fft_test/y13[31:16]} y13_real
quietly virtual signal -install /fft_test { /fft_test/y13[15:0]} y13_imag
quietly virtual signal -install /fft_test { /fft_test/y14[31:16]} y14_real
quietly virtual signal -install /fft_test { /fft_test/y14[15:0]} y14_imag
quietly virtual signal -install /fft_test { /fft_test/y15[31:16]} y15_real
quietly virtual signal -install /fft_test { /fft_test/y15[15:0]} y15_imag
quietly WaveActivateNextPane {} 0
add wave -noupdate /fft_test/CLK
add wave -noupdate /fft_test/RST
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x0_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x0_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x1_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x1_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x3_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x3_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x4_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x4_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x5_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x5_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x6_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x6_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x7_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x7_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x8_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x8_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x9_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x9_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x10_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x10_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x11_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x11_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x12_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x12_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x13_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x13_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x14_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x14_imag
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x15_real
add wave -noupdate -color Yellow -height 20 -itemcolor Yellow -radix fixed#8#decimal#signed /fft_test/x15_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y0_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y0_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y1_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y1_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y2_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y2_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y3_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y3_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y4_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y4_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y5_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y5_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y6_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y6_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y7_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y7_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y8_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y8_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y9_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y9_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y10_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y10_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y11_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y11_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y12_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y12_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y13_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y13_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y14_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y14_imag
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y15_real
add wave -noupdate -color White -height 20 -itemcolor White -radix fixed#8#decimal#signed /fft_test/y15_imag
add wave -noupdate -radix decimal -childformat {{{/fft_test/x0[31]} -radix decimal} {{/fft_test/x0[30]} -radix decimal} {{/fft_test/x0[29]} -radix decimal} {{/fft_test/x0[28]} -radix decimal} {{/fft_test/x0[27]} -radix decimal} {{/fft_test/x0[26]} -radix decimal} {{/fft_test/x0[25]} -radix decimal} {{/fft_test/x0[24]} -radix decimal} {{/fft_test/x0[23]} -radix decimal} {{/fft_test/x0[22]} -radix decimal} {{/fft_test/x0[21]} -radix decimal} {{/fft_test/x0[20]} -radix decimal} {{/fft_test/x0[19]} -radix decimal} {{/fft_test/x0[18]} -radix decimal} {{/fft_test/x0[17]} -radix decimal} {{/fft_test/x0[16]} -radix decimal} {{/fft_test/x0[15]} -radix decimal} {{/fft_test/x0[14]} -radix decimal} {{/fft_test/x0[13]} -radix decimal} {{/fft_test/x0[12]} -radix decimal} {{/fft_test/x0[11]} -radix decimal} {{/fft_test/x0[10]} -radix decimal} {{/fft_test/x0[9]} -radix decimal} {{/fft_test/x0[8]} -radix decimal} {{/fft_test/x0[7]} -radix decimal} {{/fft_test/x0[6]} -radix decimal} {{/fft_test/x0[5]} -radix decimal} {{/fft_test/x0[4]} -radix decimal} {{/fft_test/x0[3]} -radix decimal} {{/fft_test/x0[2]} -radix decimal} {{/fft_test/x0[1]} -radix decimal} {{/fft_test/x0[0]} -radix decimal}} -subitemconfig {{/fft_test/x0[31]} {-radix decimal} {/fft_test/x0[30]} {-radix decimal} {/fft_test/x0[29]} {-radix decimal} {/fft_test/x0[28]} {-radix decimal} {/fft_test/x0[27]} {-radix decimal} {/fft_test/x0[26]} {-radix decimal} {/fft_test/x0[25]} {-radix decimal} {/fft_test/x0[24]} {-radix decimal} {/fft_test/x0[23]} {-radix decimal} {/fft_test/x0[22]} {-radix decimal} {/fft_test/x0[21]} {-radix decimal} {/fft_test/x0[20]} {-radix decimal} {/fft_test/x0[19]} {-radix decimal} {/fft_test/x0[18]} {-radix decimal} {/fft_test/x0[17]} {-radix decimal} {/fft_test/x0[16]} {-radix decimal} {/fft_test/x0[15]} {-radix decimal} {/fft_test/x0[14]} {-radix decimal} {/fft_test/x0[13]} {-radix decimal} {/fft_test/x0[12]} {-radix decimal} {/fft_test/x0[11]} {-radix decimal} {/fft_test/x0[10]} {-radix decimal} {/fft_test/x0[9]} {-radix decimal} {/fft_test/x0[8]} {-radix decimal} {/fft_test/x0[7]} {-radix decimal} {/fft_test/x0[6]} {-radix decimal} {/fft_test/x0[5]} {-radix decimal} {/fft_test/x0[4]} {-radix decimal} {/fft_test/x0[3]} {-radix decimal} {/fft_test/x0[2]} {-radix decimal} {/fft_test/x0[1]} {-radix decimal} {/fft_test/x0[0]} {-radix decimal}} /fft_test/x0
add wave -noupdate -radix decimal -childformat {{{/fft_test/x1[31]} -radix decimal} {{/fft_test/x1[30]} -radix decimal} {{/fft_test/x1[29]} -radix decimal} {{/fft_test/x1[28]} -radix decimal} {{/fft_test/x1[27]} -radix decimal} {{/fft_test/x1[26]} -radix decimal} {{/fft_test/x1[25]} -radix decimal} {{/fft_test/x1[24]} -radix decimal} {{/fft_test/x1[23]} -radix decimal} {{/fft_test/x1[22]} -radix decimal} {{/fft_test/x1[21]} -radix decimal} {{/fft_test/x1[20]} -radix decimal} {{/fft_test/x1[19]} -radix decimal} {{/fft_test/x1[18]} -radix decimal} {{/fft_test/x1[17]} -radix decimal} {{/fft_test/x1[16]} -radix decimal} {{/fft_test/x1[15]} -radix decimal} {{/fft_test/x1[14]} -radix decimal} {{/fft_test/x1[13]} -radix decimal} {{/fft_test/x1[12]} -radix decimal} {{/fft_test/x1[11]} -radix decimal} {{/fft_test/x1[10]} -radix decimal} {{/fft_test/x1[9]} -radix decimal} {{/fft_test/x1[8]} -radix decimal} {{/fft_test/x1[7]} -radix decimal} {{/fft_test/x1[6]} -radix decimal} {{/fft_test/x1[5]} -radix decimal} {{/fft_test/x1[4]} -radix decimal} {{/fft_test/x1[3]} -radix decimal} {{/fft_test/x1[2]} -radix decimal} {{/fft_test/x1[1]} -radix decimal} {{/fft_test/x1[0]} -radix decimal}} -subitemconfig {{/fft_test/x1[31]} {-height 15 -radix decimal} {/fft_test/x1[30]} {-height 15 -radix decimal} {/fft_test/x1[29]} {-height 15 -radix decimal} {/fft_test/x1[28]} {-height 15 -radix decimal} {/fft_test/x1[27]} {-height 15 -radix decimal} {/fft_test/x1[26]} {-height 15 -radix decimal} {/fft_test/x1[25]} {-height 15 -radix decimal} {/fft_test/x1[24]} {-height 15 -radix decimal} {/fft_test/x1[23]} {-height 15 -radix decimal} {/fft_test/x1[22]} {-height 15 -radix decimal} {/fft_test/x1[21]} {-height 15 -radix decimal} {/fft_test/x1[20]} {-height 15 -radix decimal} {/fft_test/x1[19]} {-height 15 -radix decimal} {/fft_test/x1[18]} {-height 15 -radix decimal} {/fft_test/x1[17]} {-height 15 -radix decimal} {/fft_test/x1[16]} {-height 15 -radix decimal} {/fft_test/x1[15]} {-height 15 -radix decimal} {/fft_test/x1[14]} {-height 15 -radix decimal} {/fft_test/x1[13]} {-height 15 -radix decimal} {/fft_test/x1[12]} {-height 15 -radix decimal} {/fft_test/x1[11]} {-height 15 -radix decimal} {/fft_test/x1[10]} {-height 15 -radix decimal} {/fft_test/x1[9]} {-height 15 -radix decimal} {/fft_test/x1[8]} {-height 15 -radix decimal} {/fft_test/x1[7]} {-height 15 -radix decimal} {/fft_test/x1[6]} {-height 15 -radix decimal} {/fft_test/x1[5]} {-height 15 -radix decimal} {/fft_test/x1[4]} {-height 15 -radix decimal} {/fft_test/x1[3]} {-height 15 -radix decimal} {/fft_test/x1[2]} {-height 15 -radix decimal} {/fft_test/x1[1]} {-height 15 -radix decimal} {/fft_test/x1[0]} {-height 15 -radix decimal}} /fft_test/x1
add wave -noupdate -radix decimal /fft_test/x2
add wave -noupdate -radix decimal -childformat {{{/fft_test/x3[31]} -radix decimal} {{/fft_test/x3[30]} -radix decimal} {{/fft_test/x3[29]} -radix decimal} {{/fft_test/x3[28]} -radix decimal} {{/fft_test/x3[27]} -radix decimal} {{/fft_test/x3[26]} -radix decimal} {{/fft_test/x3[25]} -radix decimal} {{/fft_test/x3[24]} -radix decimal} {{/fft_test/x3[23]} -radix decimal} {{/fft_test/x3[22]} -radix decimal} {{/fft_test/x3[21]} -radix decimal} {{/fft_test/x3[20]} -radix decimal} {{/fft_test/x3[19]} -radix decimal} {{/fft_test/x3[18]} -radix decimal} {{/fft_test/x3[17]} -radix decimal} {{/fft_test/x3[16]} -radix decimal} {{/fft_test/x3[15]} -radix decimal} {{/fft_test/x3[14]} -radix decimal} {{/fft_test/x3[13]} -radix decimal} {{/fft_test/x3[12]} -radix decimal} {{/fft_test/x3[11]} -radix decimal} {{/fft_test/x3[10]} -radix decimal} {{/fft_test/x3[9]} -radix decimal} {{/fft_test/x3[8]} -radix decimal} {{/fft_test/x3[7]} -radix decimal} {{/fft_test/x3[6]} -radix decimal} {{/fft_test/x3[5]} -radix decimal} {{/fft_test/x3[4]} -radix decimal} {{/fft_test/x3[3]} -radix decimal} {{/fft_test/x3[2]} -radix decimal} {{/fft_test/x3[1]} -radix decimal} {{/fft_test/x3[0]} -radix decimal}} -subitemconfig {{/fft_test/x3[31]} {-radix decimal} {/fft_test/x3[30]} {-radix decimal} {/fft_test/x3[29]} {-radix decimal} {/fft_test/x3[28]} {-radix decimal} {/fft_test/x3[27]} {-radix decimal} {/fft_test/x3[26]} {-radix decimal} {/fft_test/x3[25]} {-radix decimal} {/fft_test/x3[24]} {-radix decimal} {/fft_test/x3[23]} {-radix decimal} {/fft_test/x3[22]} {-radix decimal} {/fft_test/x3[21]} {-radix decimal} {/fft_test/x3[20]} {-radix decimal} {/fft_test/x3[19]} {-radix decimal} {/fft_test/x3[18]} {-radix decimal} {/fft_test/x3[17]} {-radix decimal} {/fft_test/x3[16]} {-radix decimal} {/fft_test/x3[15]} {-radix decimal} {/fft_test/x3[14]} {-radix decimal} {/fft_test/x3[13]} {-radix decimal} {/fft_test/x3[12]} {-radix decimal} {/fft_test/x3[11]} {-radix decimal} {/fft_test/x3[10]} {-radix decimal} {/fft_test/x3[9]} {-radix decimal} {/fft_test/x3[8]} {-radix decimal} {/fft_test/x3[7]} {-radix decimal} {/fft_test/x3[6]} {-radix decimal} {/fft_test/x3[5]} {-radix decimal} {/fft_test/x3[4]} {-radix decimal} {/fft_test/x3[3]} {-radix decimal} {/fft_test/x3[2]} {-radix decimal} {/fft_test/x3[1]} {-radix decimal} {/fft_test/x3[0]} {-radix decimal}} /fft_test/x3
add wave -noupdate -radix decimal -childformat {{{/fft_test/x4[31]} -radix decimal} {{/fft_test/x4[30]} -radix decimal} {{/fft_test/x4[29]} -radix decimal} {{/fft_test/x4[28]} -radix decimal} {{/fft_test/x4[27]} -radix decimal} {{/fft_test/x4[26]} -radix decimal} {{/fft_test/x4[25]} -radix decimal} {{/fft_test/x4[24]} -radix decimal} {{/fft_test/x4[23]} -radix decimal} {{/fft_test/x4[22]} -radix decimal} {{/fft_test/x4[21]} -radix decimal} {{/fft_test/x4[20]} -radix decimal} {{/fft_test/x4[19]} -radix decimal} {{/fft_test/x4[18]} -radix decimal} {{/fft_test/x4[17]} -radix decimal} {{/fft_test/x4[16]} -radix decimal} {{/fft_test/x4[15]} -radix decimal} {{/fft_test/x4[14]} -radix decimal} {{/fft_test/x4[13]} -radix decimal} {{/fft_test/x4[12]} -radix decimal} {{/fft_test/x4[11]} -radix decimal} {{/fft_test/x4[10]} -radix decimal} {{/fft_test/x4[9]} -radix decimal} {{/fft_test/x4[8]} -radix decimal} {{/fft_test/x4[7]} -radix decimal} {{/fft_test/x4[6]} -radix decimal} {{/fft_test/x4[5]} -radix decimal} {{/fft_test/x4[4]} -radix decimal} {{/fft_test/x4[3]} -radix decimal} {{/fft_test/x4[2]} -radix decimal} {{/fft_test/x4[1]} -radix decimal} {{/fft_test/x4[0]} -radix decimal}} -subitemconfig {{/fft_test/x4[31]} {-radix decimal} {/fft_test/x4[30]} {-radix decimal} {/fft_test/x4[29]} {-radix decimal} {/fft_test/x4[28]} {-radix decimal} {/fft_test/x4[27]} {-radix decimal} {/fft_test/x4[26]} {-radix decimal} {/fft_test/x4[25]} {-radix decimal} {/fft_test/x4[24]} {-radix decimal} {/fft_test/x4[23]} {-radix decimal} {/fft_test/x4[22]} {-radix decimal} {/fft_test/x4[21]} {-radix decimal} {/fft_test/x4[20]} {-radix decimal} {/fft_test/x4[19]} {-radix decimal} {/fft_test/x4[18]} {-radix decimal} {/fft_test/x4[17]} {-radix decimal} {/fft_test/x4[16]} {-radix decimal} {/fft_test/x4[15]} {-radix decimal} {/fft_test/x4[14]} {-radix decimal} {/fft_test/x4[13]} {-radix decimal} {/fft_test/x4[12]} {-radix decimal} {/fft_test/x4[11]} {-radix decimal} {/fft_test/x4[10]} {-radix decimal} {/fft_test/x4[9]} {-radix decimal} {/fft_test/x4[8]} {-radix decimal} {/fft_test/x4[7]} {-radix decimal} {/fft_test/x4[6]} {-radix decimal} {/fft_test/x4[5]} {-radix decimal} {/fft_test/x4[4]} {-radix decimal} {/fft_test/x4[3]} {-radix decimal} {/fft_test/x4[2]} {-radix decimal} {/fft_test/x4[1]} {-radix decimal} {/fft_test/x4[0]} {-radix decimal}} /fft_test/x4
add wave -noupdate -radix decimal -childformat {{{/fft_test/x5[31]} -radix decimal} {{/fft_test/x5[30]} -radix decimal} {{/fft_test/x5[29]} -radix decimal} {{/fft_test/x5[28]} -radix decimal} {{/fft_test/x5[27]} -radix decimal} {{/fft_test/x5[26]} -radix decimal} {{/fft_test/x5[25]} -radix decimal} {{/fft_test/x5[24]} -radix decimal} {{/fft_test/x5[23]} -radix decimal} {{/fft_test/x5[22]} -radix decimal} {{/fft_test/x5[21]} -radix decimal} {{/fft_test/x5[20]} -radix decimal} {{/fft_test/x5[19]} -radix decimal} {{/fft_test/x5[18]} -radix decimal} {{/fft_test/x5[17]} -radix decimal} {{/fft_test/x5[16]} -radix decimal} {{/fft_test/x5[15]} -radix decimal} {{/fft_test/x5[14]} -radix decimal} {{/fft_test/x5[13]} -radix decimal} {{/fft_test/x5[12]} -radix decimal} {{/fft_test/x5[11]} -radix decimal} {{/fft_test/x5[10]} -radix decimal} {{/fft_test/x5[9]} -radix decimal} {{/fft_test/x5[8]} -radix decimal} {{/fft_test/x5[7]} -radix decimal} {{/fft_test/x5[6]} -radix decimal} {{/fft_test/x5[5]} -radix decimal} {{/fft_test/x5[4]} -radix decimal} {{/fft_test/x5[3]} -radix decimal} {{/fft_test/x5[2]} -radix decimal} {{/fft_test/x5[1]} -radix decimal} {{/fft_test/x5[0]} -radix decimal}} -subitemconfig {{/fft_test/x5[31]} {-radix decimal} {/fft_test/x5[30]} {-radix decimal} {/fft_test/x5[29]} {-radix decimal} {/fft_test/x5[28]} {-radix decimal} {/fft_test/x5[27]} {-radix decimal} {/fft_test/x5[26]} {-radix decimal} {/fft_test/x5[25]} {-radix decimal} {/fft_test/x5[24]} {-radix decimal} {/fft_test/x5[23]} {-radix decimal} {/fft_test/x5[22]} {-radix decimal} {/fft_test/x5[21]} {-radix decimal} {/fft_test/x5[20]} {-radix decimal} {/fft_test/x5[19]} {-radix decimal} {/fft_test/x5[18]} {-radix decimal} {/fft_test/x5[17]} {-radix decimal} {/fft_test/x5[16]} {-radix decimal} {/fft_test/x5[15]} {-radix decimal} {/fft_test/x5[14]} {-radix decimal} {/fft_test/x5[13]} {-radix decimal} {/fft_test/x5[12]} {-radix decimal} {/fft_test/x5[11]} {-radix decimal} {/fft_test/x5[10]} {-radix decimal} {/fft_test/x5[9]} {-radix decimal} {/fft_test/x5[8]} {-radix decimal} {/fft_test/x5[7]} {-radix decimal} {/fft_test/x5[6]} {-radix decimal} {/fft_test/x5[5]} {-radix decimal} {/fft_test/x5[4]} {-radix decimal} {/fft_test/x5[3]} {-radix decimal} {/fft_test/x5[2]} {-radix decimal} {/fft_test/x5[1]} {-radix decimal} {/fft_test/x5[0]} {-radix decimal}} /fft_test/x5
add wave -noupdate -radix decimal -childformat {{{/fft_test/x6[31]} -radix decimal} {{/fft_test/x6[30]} -radix decimal} {{/fft_test/x6[29]} -radix decimal} {{/fft_test/x6[28]} -radix decimal} {{/fft_test/x6[27]} -radix decimal} {{/fft_test/x6[26]} -radix decimal} {{/fft_test/x6[25]} -radix decimal} {{/fft_test/x6[24]} -radix decimal} {{/fft_test/x6[23]} -radix decimal} {{/fft_test/x6[22]} -radix decimal} {{/fft_test/x6[21]} -radix decimal} {{/fft_test/x6[20]} -radix decimal} {{/fft_test/x6[19]} -radix decimal} {{/fft_test/x6[18]} -radix decimal} {{/fft_test/x6[17]} -radix decimal} {{/fft_test/x6[16]} -radix decimal} {{/fft_test/x6[15]} -radix decimal} {{/fft_test/x6[14]} -radix decimal} {{/fft_test/x6[13]} -radix decimal} {{/fft_test/x6[12]} -radix decimal} {{/fft_test/x6[11]} -radix decimal} {{/fft_test/x6[10]} -radix decimal} {{/fft_test/x6[9]} -radix decimal} {{/fft_test/x6[8]} -radix decimal} {{/fft_test/x6[7]} -radix decimal} {{/fft_test/x6[6]} -radix decimal} {{/fft_test/x6[5]} -radix decimal} {{/fft_test/x6[4]} -radix decimal} {{/fft_test/x6[3]} -radix decimal} {{/fft_test/x6[2]} -radix decimal} {{/fft_test/x6[1]} -radix decimal} {{/fft_test/x6[0]} -radix decimal}} -subitemconfig {{/fft_test/x6[31]} {-radix decimal} {/fft_test/x6[30]} {-radix decimal} {/fft_test/x6[29]} {-radix decimal} {/fft_test/x6[28]} {-radix decimal} {/fft_test/x6[27]} {-radix decimal} {/fft_test/x6[26]} {-radix decimal} {/fft_test/x6[25]} {-radix decimal} {/fft_test/x6[24]} {-radix decimal} {/fft_test/x6[23]} {-radix decimal} {/fft_test/x6[22]} {-radix decimal} {/fft_test/x6[21]} {-radix decimal} {/fft_test/x6[20]} {-radix decimal} {/fft_test/x6[19]} {-radix decimal} {/fft_test/x6[18]} {-radix decimal} {/fft_test/x6[17]} {-radix decimal} {/fft_test/x6[16]} {-radix decimal} {/fft_test/x6[15]} {-radix decimal} {/fft_test/x6[14]} {-radix decimal} {/fft_test/x6[13]} {-radix decimal} {/fft_test/x6[12]} {-radix decimal} {/fft_test/x6[11]} {-radix decimal} {/fft_test/x6[10]} {-radix decimal} {/fft_test/x6[9]} {-radix decimal} {/fft_test/x6[8]} {-radix decimal} {/fft_test/x6[7]} {-radix decimal} {/fft_test/x6[6]} {-radix decimal} {/fft_test/x6[5]} {-radix decimal} {/fft_test/x6[4]} {-radix decimal} {/fft_test/x6[3]} {-radix decimal} {/fft_test/x6[2]} {-radix decimal} {/fft_test/x6[1]} {-radix decimal} {/fft_test/x6[0]} {-radix decimal}} /fft_test/x6
add wave -noupdate -radix decimal -childformat {{{/fft_test/x7[31]} -radix decimal} {{/fft_test/x7[30]} -radix decimal} {{/fft_test/x7[29]} -radix decimal} {{/fft_test/x7[28]} -radix decimal} {{/fft_test/x7[27]} -radix decimal} {{/fft_test/x7[26]} -radix decimal} {{/fft_test/x7[25]} -radix decimal} {{/fft_test/x7[24]} -radix decimal} {{/fft_test/x7[23]} -radix decimal} {{/fft_test/x7[22]} -radix decimal} {{/fft_test/x7[21]} -radix decimal} {{/fft_test/x7[20]} -radix decimal} {{/fft_test/x7[19]} -radix decimal} {{/fft_test/x7[18]} -radix decimal} {{/fft_test/x7[17]} -radix decimal} {{/fft_test/x7[16]} -radix decimal} {{/fft_test/x7[15]} -radix decimal} {{/fft_test/x7[14]} -radix decimal} {{/fft_test/x7[13]} -radix decimal} {{/fft_test/x7[12]} -radix decimal} {{/fft_test/x7[11]} -radix decimal} {{/fft_test/x7[10]} -radix decimal} {{/fft_test/x7[9]} -radix decimal} {{/fft_test/x7[8]} -radix decimal} {{/fft_test/x7[7]} -radix decimal} {{/fft_test/x7[6]} -radix decimal} {{/fft_test/x7[5]} -radix decimal} {{/fft_test/x7[4]} -radix decimal} {{/fft_test/x7[3]} -radix decimal} {{/fft_test/x7[2]} -radix decimal} {{/fft_test/x7[1]} -radix decimal} {{/fft_test/x7[0]} -radix decimal}} -subitemconfig {{/fft_test/x7[31]} {-radix decimal} {/fft_test/x7[30]} {-radix decimal} {/fft_test/x7[29]} {-radix decimal} {/fft_test/x7[28]} {-radix decimal} {/fft_test/x7[27]} {-radix decimal} {/fft_test/x7[26]} {-radix decimal} {/fft_test/x7[25]} {-radix decimal} {/fft_test/x7[24]} {-radix decimal} {/fft_test/x7[23]} {-radix decimal} {/fft_test/x7[22]} {-radix decimal} {/fft_test/x7[21]} {-radix decimal} {/fft_test/x7[20]} {-radix decimal} {/fft_test/x7[19]} {-radix decimal} {/fft_test/x7[18]} {-radix decimal} {/fft_test/x7[17]} {-radix decimal} {/fft_test/x7[16]} {-radix decimal} {/fft_test/x7[15]} {-radix decimal} {/fft_test/x7[14]} {-radix decimal} {/fft_test/x7[13]} {-radix decimal} {/fft_test/x7[12]} {-radix decimal} {/fft_test/x7[11]} {-radix decimal} {/fft_test/x7[10]} {-radix decimal} {/fft_test/x7[9]} {-radix decimal} {/fft_test/x7[8]} {-radix decimal} {/fft_test/x7[7]} {-radix decimal} {/fft_test/x7[6]} {-radix decimal} {/fft_test/x7[5]} {-radix decimal} {/fft_test/x7[4]} {-radix decimal} {/fft_test/x7[3]} {-radix decimal} {/fft_test/x7[2]} {-radix decimal} {/fft_test/x7[1]} {-radix decimal} {/fft_test/x7[0]} {-radix decimal}} /fft_test/x7
add wave -noupdate -radix decimal -childformat {{{/fft_test/x8[31]} -radix decimal} {{/fft_test/x8[30]} -radix decimal} {{/fft_test/x8[29]} -radix decimal} {{/fft_test/x8[28]} -radix decimal} {{/fft_test/x8[27]} -radix decimal} {{/fft_test/x8[26]} -radix decimal} {{/fft_test/x8[25]} -radix decimal} {{/fft_test/x8[24]} -radix decimal} {{/fft_test/x8[23]} -radix decimal} {{/fft_test/x8[22]} -radix decimal} {{/fft_test/x8[21]} -radix decimal} {{/fft_test/x8[20]} -radix decimal} {{/fft_test/x8[19]} -radix decimal} {{/fft_test/x8[18]} -radix decimal} {{/fft_test/x8[17]} -radix decimal} {{/fft_test/x8[16]} -radix decimal} {{/fft_test/x8[15]} -radix decimal} {{/fft_test/x8[14]} -radix decimal} {{/fft_test/x8[13]} -radix decimal} {{/fft_test/x8[12]} -radix decimal} {{/fft_test/x8[11]} -radix decimal} {{/fft_test/x8[10]} -radix decimal} {{/fft_test/x8[9]} -radix decimal} {{/fft_test/x8[8]} -radix decimal} {{/fft_test/x8[7]} -radix decimal} {{/fft_test/x8[6]} -radix decimal} {{/fft_test/x8[5]} -radix decimal} {{/fft_test/x8[4]} -radix decimal} {{/fft_test/x8[3]} -radix decimal} {{/fft_test/x8[2]} -radix decimal} {{/fft_test/x8[1]} -radix decimal} {{/fft_test/x8[0]} -radix decimal}} -subitemconfig {{/fft_test/x8[31]} {-radix decimal} {/fft_test/x8[30]} {-radix decimal} {/fft_test/x8[29]} {-radix decimal} {/fft_test/x8[28]} {-radix decimal} {/fft_test/x8[27]} {-radix decimal} {/fft_test/x8[26]} {-radix decimal} {/fft_test/x8[25]} {-radix decimal} {/fft_test/x8[24]} {-radix decimal} {/fft_test/x8[23]} {-radix decimal} {/fft_test/x8[22]} {-radix decimal} {/fft_test/x8[21]} {-radix decimal} {/fft_test/x8[20]} {-radix decimal} {/fft_test/x8[19]} {-radix decimal} {/fft_test/x8[18]} {-radix decimal} {/fft_test/x8[17]} {-radix decimal} {/fft_test/x8[16]} {-radix decimal} {/fft_test/x8[15]} {-radix decimal} {/fft_test/x8[14]} {-radix decimal} {/fft_test/x8[13]} {-radix decimal} {/fft_test/x8[12]} {-radix decimal} {/fft_test/x8[11]} {-radix decimal} {/fft_test/x8[10]} {-radix decimal} {/fft_test/x8[9]} {-radix decimal} {/fft_test/x8[8]} {-radix decimal} {/fft_test/x8[7]} {-radix decimal} {/fft_test/x8[6]} {-radix decimal} {/fft_test/x8[5]} {-radix decimal} {/fft_test/x8[4]} {-radix decimal} {/fft_test/x8[3]} {-radix decimal} {/fft_test/x8[2]} {-radix decimal} {/fft_test/x8[1]} {-radix decimal} {/fft_test/x8[0]} {-radix decimal}} /fft_test/x8
add wave -noupdate -radix decimal -childformat {{{/fft_test/x9[31]} -radix decimal} {{/fft_test/x9[30]} -radix decimal} {{/fft_test/x9[29]} -radix decimal} {{/fft_test/x9[28]} -radix decimal} {{/fft_test/x9[27]} -radix decimal} {{/fft_test/x9[26]} -radix decimal} {{/fft_test/x9[25]} -radix decimal} {{/fft_test/x9[24]} -radix decimal} {{/fft_test/x9[23]} -radix decimal} {{/fft_test/x9[22]} -radix decimal} {{/fft_test/x9[21]} -radix decimal} {{/fft_test/x9[20]} -radix decimal} {{/fft_test/x9[19]} -radix decimal} {{/fft_test/x9[18]} -radix decimal} {{/fft_test/x9[17]} -radix decimal} {{/fft_test/x9[16]} -radix decimal} {{/fft_test/x9[15]} -radix decimal} {{/fft_test/x9[14]} -radix decimal} {{/fft_test/x9[13]} -radix decimal} {{/fft_test/x9[12]} -radix decimal} {{/fft_test/x9[11]} -radix decimal} {{/fft_test/x9[10]} -radix decimal} {{/fft_test/x9[9]} -radix decimal} {{/fft_test/x9[8]} -radix decimal} {{/fft_test/x9[7]} -radix decimal} {{/fft_test/x9[6]} -radix decimal} {{/fft_test/x9[5]} -radix decimal} {{/fft_test/x9[4]} -radix decimal} {{/fft_test/x9[3]} -radix decimal} {{/fft_test/x9[2]} -radix decimal} {{/fft_test/x9[1]} -radix decimal} {{/fft_test/x9[0]} -radix decimal}} -subitemconfig {{/fft_test/x9[31]} {-radix decimal} {/fft_test/x9[30]} {-radix decimal} {/fft_test/x9[29]} {-radix decimal} {/fft_test/x9[28]} {-radix decimal} {/fft_test/x9[27]} {-radix decimal} {/fft_test/x9[26]} {-radix decimal} {/fft_test/x9[25]} {-radix decimal} {/fft_test/x9[24]} {-radix decimal} {/fft_test/x9[23]} {-radix decimal} {/fft_test/x9[22]} {-radix decimal} {/fft_test/x9[21]} {-radix decimal} {/fft_test/x9[20]} {-radix decimal} {/fft_test/x9[19]} {-radix decimal} {/fft_test/x9[18]} {-radix decimal} {/fft_test/x9[17]} {-radix decimal} {/fft_test/x9[16]} {-radix decimal} {/fft_test/x9[15]} {-radix decimal} {/fft_test/x9[14]} {-radix decimal} {/fft_test/x9[13]} {-radix decimal} {/fft_test/x9[12]} {-radix decimal} {/fft_test/x9[11]} {-radix decimal} {/fft_test/x9[10]} {-radix decimal} {/fft_test/x9[9]} {-radix decimal} {/fft_test/x9[8]} {-radix decimal} {/fft_test/x9[7]} {-radix decimal} {/fft_test/x9[6]} {-radix decimal} {/fft_test/x9[5]} {-radix decimal} {/fft_test/x9[4]} {-radix decimal} {/fft_test/x9[3]} {-radix decimal} {/fft_test/x9[2]} {-radix decimal} {/fft_test/x9[1]} {-radix decimal} {/fft_test/x9[0]} {-radix decimal}} /fft_test/x9
add wave -noupdate -radix decimal -childformat {{{/fft_test/x10[31]} -radix decimal} {{/fft_test/x10[30]} -radix decimal} {{/fft_test/x10[29]} -radix decimal} {{/fft_test/x10[28]} -radix decimal} {{/fft_test/x10[27]} -radix decimal} {{/fft_test/x10[26]} -radix decimal} {{/fft_test/x10[25]} -radix decimal} {{/fft_test/x10[24]} -radix decimal} {{/fft_test/x10[23]} -radix decimal} {{/fft_test/x10[22]} -radix decimal} {{/fft_test/x10[21]} -radix decimal} {{/fft_test/x10[20]} -radix decimal} {{/fft_test/x10[19]} -radix decimal} {{/fft_test/x10[18]} -radix decimal} {{/fft_test/x10[17]} -radix decimal} {{/fft_test/x10[16]} -radix decimal} {{/fft_test/x10[15]} -radix decimal} {{/fft_test/x10[14]} -radix decimal} {{/fft_test/x10[13]} -radix decimal} {{/fft_test/x10[12]} -radix decimal} {{/fft_test/x10[11]} -radix decimal} {{/fft_test/x10[10]} -radix decimal} {{/fft_test/x10[9]} -radix decimal} {{/fft_test/x10[8]} -radix decimal} {{/fft_test/x10[7]} -radix decimal} {{/fft_test/x10[6]} -radix decimal} {{/fft_test/x10[5]} -radix decimal} {{/fft_test/x10[4]} -radix decimal} {{/fft_test/x10[3]} -radix decimal} {{/fft_test/x10[2]} -radix decimal} {{/fft_test/x10[1]} -radix decimal} {{/fft_test/x10[0]} -radix decimal}} -subitemconfig {{/fft_test/x10[31]} {-radix decimal} {/fft_test/x10[30]} {-radix decimal} {/fft_test/x10[29]} {-radix decimal} {/fft_test/x10[28]} {-radix decimal} {/fft_test/x10[27]} {-radix decimal} {/fft_test/x10[26]} {-radix decimal} {/fft_test/x10[25]} {-radix decimal} {/fft_test/x10[24]} {-radix decimal} {/fft_test/x10[23]} {-radix decimal} {/fft_test/x10[22]} {-radix decimal} {/fft_test/x10[21]} {-radix decimal} {/fft_test/x10[20]} {-radix decimal} {/fft_test/x10[19]} {-radix decimal} {/fft_test/x10[18]} {-radix decimal} {/fft_test/x10[17]} {-radix decimal} {/fft_test/x10[16]} {-radix decimal} {/fft_test/x10[15]} {-radix decimal} {/fft_test/x10[14]} {-radix decimal} {/fft_test/x10[13]} {-radix decimal} {/fft_test/x10[12]} {-radix decimal} {/fft_test/x10[11]} {-radix decimal} {/fft_test/x10[10]} {-radix decimal} {/fft_test/x10[9]} {-radix decimal} {/fft_test/x10[8]} {-radix decimal} {/fft_test/x10[7]} {-radix decimal} {/fft_test/x10[6]} {-radix decimal} {/fft_test/x10[5]} {-radix decimal} {/fft_test/x10[4]} {-radix decimal} {/fft_test/x10[3]} {-radix decimal} {/fft_test/x10[2]} {-radix decimal} {/fft_test/x10[1]} {-radix decimal} {/fft_test/x10[0]} {-radix decimal}} /fft_test/x10
add wave -noupdate -radix decimal -childformat {{{/fft_test/x11[31]} -radix decimal} {{/fft_test/x11[30]} -radix decimal} {{/fft_test/x11[29]} -radix decimal} {{/fft_test/x11[28]} -radix decimal} {{/fft_test/x11[27]} -radix decimal} {{/fft_test/x11[26]} -radix decimal} {{/fft_test/x11[25]} -radix decimal} {{/fft_test/x11[24]} -radix decimal} {{/fft_test/x11[23]} -radix decimal} {{/fft_test/x11[22]} -radix decimal} {{/fft_test/x11[21]} -radix decimal} {{/fft_test/x11[20]} -radix decimal} {{/fft_test/x11[19]} -radix decimal} {{/fft_test/x11[18]} -radix decimal} {{/fft_test/x11[17]} -radix decimal} {{/fft_test/x11[16]} -radix decimal} {{/fft_test/x11[15]} -radix decimal} {{/fft_test/x11[14]} -radix decimal} {{/fft_test/x11[13]} -radix decimal} {{/fft_test/x11[12]} -radix decimal} {{/fft_test/x11[11]} -radix decimal} {{/fft_test/x11[10]} -radix decimal} {{/fft_test/x11[9]} -radix decimal} {{/fft_test/x11[8]} -radix decimal} {{/fft_test/x11[7]} -radix decimal} {{/fft_test/x11[6]} -radix decimal} {{/fft_test/x11[5]} -radix decimal} {{/fft_test/x11[4]} -radix decimal} {{/fft_test/x11[3]} -radix decimal} {{/fft_test/x11[2]} -radix decimal} {{/fft_test/x11[1]} -radix decimal} {{/fft_test/x11[0]} -radix decimal}} -subitemconfig {{/fft_test/x11[31]} {-radix decimal} {/fft_test/x11[30]} {-radix decimal} {/fft_test/x11[29]} {-radix decimal} {/fft_test/x11[28]} {-radix decimal} {/fft_test/x11[27]} {-radix decimal} {/fft_test/x11[26]} {-radix decimal} {/fft_test/x11[25]} {-radix decimal} {/fft_test/x11[24]} {-radix decimal} {/fft_test/x11[23]} {-radix decimal} {/fft_test/x11[22]} {-radix decimal} {/fft_test/x11[21]} {-radix decimal} {/fft_test/x11[20]} {-radix decimal} {/fft_test/x11[19]} {-radix decimal} {/fft_test/x11[18]} {-radix decimal} {/fft_test/x11[17]} {-radix decimal} {/fft_test/x11[16]} {-radix decimal} {/fft_test/x11[15]} {-radix decimal} {/fft_test/x11[14]} {-radix decimal} {/fft_test/x11[13]} {-radix decimal} {/fft_test/x11[12]} {-radix decimal} {/fft_test/x11[11]} {-radix decimal} {/fft_test/x11[10]} {-radix decimal} {/fft_test/x11[9]} {-radix decimal} {/fft_test/x11[8]} {-radix decimal} {/fft_test/x11[7]} {-radix decimal} {/fft_test/x11[6]} {-radix decimal} {/fft_test/x11[5]} {-radix decimal} {/fft_test/x11[4]} {-radix decimal} {/fft_test/x11[3]} {-radix decimal} {/fft_test/x11[2]} {-radix decimal} {/fft_test/x11[1]} {-radix decimal} {/fft_test/x11[0]} {-radix decimal}} /fft_test/x11
add wave -noupdate -radix decimal -childformat {{{/fft_test/x12[31]} -radix decimal} {{/fft_test/x12[30]} -radix decimal} {{/fft_test/x12[29]} -radix decimal} {{/fft_test/x12[28]} -radix decimal} {{/fft_test/x12[27]} -radix decimal} {{/fft_test/x12[26]} -radix decimal} {{/fft_test/x12[25]} -radix decimal} {{/fft_test/x12[24]} -radix decimal} {{/fft_test/x12[23]} -radix decimal} {{/fft_test/x12[22]} -radix decimal} {{/fft_test/x12[21]} -radix decimal} {{/fft_test/x12[20]} -radix decimal} {{/fft_test/x12[19]} -radix decimal} {{/fft_test/x12[18]} -radix decimal} {{/fft_test/x12[17]} -radix decimal} {{/fft_test/x12[16]} -radix decimal} {{/fft_test/x12[15]} -radix decimal} {{/fft_test/x12[14]} -radix decimal} {{/fft_test/x12[13]} -radix decimal} {{/fft_test/x12[12]} -radix decimal} {{/fft_test/x12[11]} -radix decimal} {{/fft_test/x12[10]} -radix decimal} {{/fft_test/x12[9]} -radix decimal} {{/fft_test/x12[8]} -radix decimal} {{/fft_test/x12[7]} -radix decimal} {{/fft_test/x12[6]} -radix decimal} {{/fft_test/x12[5]} -radix decimal} {{/fft_test/x12[4]} -radix decimal} {{/fft_test/x12[3]} -radix decimal} {{/fft_test/x12[2]} -radix decimal} {{/fft_test/x12[1]} -radix decimal} {{/fft_test/x12[0]} -radix decimal}} -subitemconfig {{/fft_test/x12[31]} {-radix decimal} {/fft_test/x12[30]} {-radix decimal} {/fft_test/x12[29]} {-radix decimal} {/fft_test/x12[28]} {-radix decimal} {/fft_test/x12[27]} {-radix decimal} {/fft_test/x12[26]} {-radix decimal} {/fft_test/x12[25]} {-radix decimal} {/fft_test/x12[24]} {-radix decimal} {/fft_test/x12[23]} {-radix decimal} {/fft_test/x12[22]} {-radix decimal} {/fft_test/x12[21]} {-radix decimal} {/fft_test/x12[20]} {-radix decimal} {/fft_test/x12[19]} {-radix decimal} {/fft_test/x12[18]} {-radix decimal} {/fft_test/x12[17]} {-radix decimal} {/fft_test/x12[16]} {-radix decimal} {/fft_test/x12[15]} {-radix decimal} {/fft_test/x12[14]} {-radix decimal} {/fft_test/x12[13]} {-radix decimal} {/fft_test/x12[12]} {-radix decimal} {/fft_test/x12[11]} {-radix decimal} {/fft_test/x12[10]} {-radix decimal} {/fft_test/x12[9]} {-radix decimal} {/fft_test/x12[8]} {-radix decimal} {/fft_test/x12[7]} {-radix decimal} {/fft_test/x12[6]} {-radix decimal} {/fft_test/x12[5]} {-radix decimal} {/fft_test/x12[4]} {-radix decimal} {/fft_test/x12[3]} {-radix decimal} {/fft_test/x12[2]} {-radix decimal} {/fft_test/x12[1]} {-radix decimal} {/fft_test/x12[0]} {-radix decimal}} /fft_test/x12
add wave -noupdate -radix decimal -childformat {{{/fft_test/x13[31]} -radix decimal} {{/fft_test/x13[30]} -radix decimal} {{/fft_test/x13[29]} -radix decimal} {{/fft_test/x13[28]} -radix decimal} {{/fft_test/x13[27]} -radix decimal} {{/fft_test/x13[26]} -radix decimal} {{/fft_test/x13[25]} -radix decimal} {{/fft_test/x13[24]} -radix decimal} {{/fft_test/x13[23]} -radix decimal} {{/fft_test/x13[22]} -radix decimal} {{/fft_test/x13[21]} -radix decimal} {{/fft_test/x13[20]} -radix decimal} {{/fft_test/x13[19]} -radix decimal} {{/fft_test/x13[18]} -radix decimal} {{/fft_test/x13[17]} -radix decimal} {{/fft_test/x13[16]} -radix decimal} {{/fft_test/x13[15]} -radix decimal} {{/fft_test/x13[14]} -radix decimal} {{/fft_test/x13[13]} -radix decimal} {{/fft_test/x13[12]} -radix decimal} {{/fft_test/x13[11]} -radix decimal} {{/fft_test/x13[10]} -radix decimal} {{/fft_test/x13[9]} -radix decimal} {{/fft_test/x13[8]} -radix decimal} {{/fft_test/x13[7]} -radix decimal} {{/fft_test/x13[6]} -radix decimal} {{/fft_test/x13[5]} -radix decimal} {{/fft_test/x13[4]} -radix decimal} {{/fft_test/x13[3]} -radix decimal} {{/fft_test/x13[2]} -radix decimal} {{/fft_test/x13[1]} -radix decimal} {{/fft_test/x13[0]} -radix decimal}} -subitemconfig {{/fft_test/x13[31]} {-radix decimal} {/fft_test/x13[30]} {-radix decimal} {/fft_test/x13[29]} {-radix decimal} {/fft_test/x13[28]} {-radix decimal} {/fft_test/x13[27]} {-radix decimal} {/fft_test/x13[26]} {-radix decimal} {/fft_test/x13[25]} {-radix decimal} {/fft_test/x13[24]} {-radix decimal} {/fft_test/x13[23]} {-radix decimal} {/fft_test/x13[22]} {-radix decimal} {/fft_test/x13[21]} {-radix decimal} {/fft_test/x13[20]} {-radix decimal} {/fft_test/x13[19]} {-radix decimal} {/fft_test/x13[18]} {-radix decimal} {/fft_test/x13[17]} {-radix decimal} {/fft_test/x13[16]} {-radix decimal} {/fft_test/x13[15]} {-radix decimal} {/fft_test/x13[14]} {-radix decimal} {/fft_test/x13[13]} {-radix decimal} {/fft_test/x13[12]} {-radix decimal} {/fft_test/x13[11]} {-radix decimal} {/fft_test/x13[10]} {-radix decimal} {/fft_test/x13[9]} {-radix decimal} {/fft_test/x13[8]} {-radix decimal} {/fft_test/x13[7]} {-radix decimal} {/fft_test/x13[6]} {-radix decimal} {/fft_test/x13[5]} {-radix decimal} {/fft_test/x13[4]} {-radix decimal} {/fft_test/x13[3]} {-radix decimal} {/fft_test/x13[2]} {-radix decimal} {/fft_test/x13[1]} {-radix decimal} {/fft_test/x13[0]} {-radix decimal}} /fft_test/x13
add wave -noupdate -radix decimal -childformat {{{/fft_test/x14[31]} -radix decimal} {{/fft_test/x14[30]} -radix decimal} {{/fft_test/x14[29]} -radix decimal} {{/fft_test/x14[28]} -radix decimal} {{/fft_test/x14[27]} -radix decimal} {{/fft_test/x14[26]} -radix decimal} {{/fft_test/x14[25]} -radix decimal} {{/fft_test/x14[24]} -radix decimal} {{/fft_test/x14[23]} -radix decimal} {{/fft_test/x14[22]} -radix decimal} {{/fft_test/x14[21]} -radix decimal} {{/fft_test/x14[20]} -radix decimal} {{/fft_test/x14[19]} -radix decimal} {{/fft_test/x14[18]} -radix decimal} {{/fft_test/x14[17]} -radix decimal} {{/fft_test/x14[16]} -radix decimal} {{/fft_test/x14[15]} -radix decimal} {{/fft_test/x14[14]} -radix decimal} {{/fft_test/x14[13]} -radix decimal} {{/fft_test/x14[12]} -radix decimal} {{/fft_test/x14[11]} -radix decimal} {{/fft_test/x14[10]} -radix decimal} {{/fft_test/x14[9]} -radix decimal} {{/fft_test/x14[8]} -radix decimal} {{/fft_test/x14[7]} -radix decimal} {{/fft_test/x14[6]} -radix decimal} {{/fft_test/x14[5]} -radix decimal} {{/fft_test/x14[4]} -radix decimal} {{/fft_test/x14[3]} -radix decimal} {{/fft_test/x14[2]} -radix decimal} {{/fft_test/x14[1]} -radix decimal} {{/fft_test/x14[0]} -radix decimal}} -subitemconfig {{/fft_test/x14[31]} {-radix decimal} {/fft_test/x14[30]} {-radix decimal} {/fft_test/x14[29]} {-radix decimal} {/fft_test/x14[28]} {-radix decimal} {/fft_test/x14[27]} {-radix decimal} {/fft_test/x14[26]} {-radix decimal} {/fft_test/x14[25]} {-radix decimal} {/fft_test/x14[24]} {-radix decimal} {/fft_test/x14[23]} {-radix decimal} {/fft_test/x14[22]} {-radix decimal} {/fft_test/x14[21]} {-radix decimal} {/fft_test/x14[20]} {-radix decimal} {/fft_test/x14[19]} {-radix decimal} {/fft_test/x14[18]} {-radix decimal} {/fft_test/x14[17]} {-radix decimal} {/fft_test/x14[16]} {-radix decimal} {/fft_test/x14[15]} {-radix decimal} {/fft_test/x14[14]} {-radix decimal} {/fft_test/x14[13]} {-radix decimal} {/fft_test/x14[12]} {-radix decimal} {/fft_test/x14[11]} {-radix decimal} {/fft_test/x14[10]} {-radix decimal} {/fft_test/x14[9]} {-radix decimal} {/fft_test/x14[8]} {-radix decimal} {/fft_test/x14[7]} {-radix decimal} {/fft_test/x14[6]} {-radix decimal} {/fft_test/x14[5]} {-radix decimal} {/fft_test/x14[4]} {-radix decimal} {/fft_test/x14[3]} {-radix decimal} {/fft_test/x14[2]} {-radix decimal} {/fft_test/x14[1]} {-radix decimal} {/fft_test/x14[0]} {-radix decimal}} /fft_test/x14
add wave -noupdate -radix decimal -childformat {{{/fft_test/x15[31]} -radix decimal} {{/fft_test/x15[30]} -radix decimal} {{/fft_test/x15[29]} -radix decimal} {{/fft_test/x15[28]} -radix decimal} {{/fft_test/x15[27]} -radix decimal} {{/fft_test/x15[26]} -radix decimal} {{/fft_test/x15[25]} -radix decimal} {{/fft_test/x15[24]} -radix decimal} {{/fft_test/x15[23]} -radix decimal} {{/fft_test/x15[22]} -radix decimal} {{/fft_test/x15[21]} -radix decimal} {{/fft_test/x15[20]} -radix decimal} {{/fft_test/x15[19]} -radix decimal} {{/fft_test/x15[18]} -radix decimal} {{/fft_test/x15[17]} -radix decimal} {{/fft_test/x15[16]} -radix decimal} {{/fft_test/x15[15]} -radix decimal} {{/fft_test/x15[14]} -radix decimal} {{/fft_test/x15[13]} -radix decimal} {{/fft_test/x15[12]} -radix decimal} {{/fft_test/x15[11]} -radix decimal} {{/fft_test/x15[10]} -radix decimal} {{/fft_test/x15[9]} -radix decimal} {{/fft_test/x15[8]} -radix decimal} {{/fft_test/x15[7]} -radix decimal} {{/fft_test/x15[6]} -radix decimal} {{/fft_test/x15[5]} -radix decimal} {{/fft_test/x15[4]} -radix decimal} {{/fft_test/x15[3]} -radix decimal} {{/fft_test/x15[2]} -radix decimal} {{/fft_test/x15[1]} -radix decimal} {{/fft_test/x15[0]} -radix decimal}} -subitemconfig {{/fft_test/x15[31]} {-radix decimal} {/fft_test/x15[30]} {-radix decimal} {/fft_test/x15[29]} {-radix decimal} {/fft_test/x15[28]} {-radix decimal} {/fft_test/x15[27]} {-radix decimal} {/fft_test/x15[26]} {-radix decimal} {/fft_test/x15[25]} {-radix decimal} {/fft_test/x15[24]} {-radix decimal} {/fft_test/x15[23]} {-radix decimal} {/fft_test/x15[22]} {-radix decimal} {/fft_test/x15[21]} {-radix decimal} {/fft_test/x15[20]} {-radix decimal} {/fft_test/x15[19]} {-radix decimal} {/fft_test/x15[18]} {-radix decimal} {/fft_test/x15[17]} {-radix decimal} {/fft_test/x15[16]} {-radix decimal} {/fft_test/x15[15]} {-radix decimal} {/fft_test/x15[14]} {-radix decimal} {/fft_test/x15[13]} {-radix decimal} {/fft_test/x15[12]} {-radix decimal} {/fft_test/x15[11]} {-radix decimal} {/fft_test/x15[10]} {-radix decimal} {/fft_test/x15[9]} {-radix decimal} {/fft_test/x15[8]} {-radix decimal} {/fft_test/x15[7]} {-radix decimal} {/fft_test/x15[6]} {-radix decimal} {/fft_test/x15[5]} {-radix decimal} {/fft_test/x15[4]} {-radix decimal} {/fft_test/x15[3]} {-radix decimal} {/fft_test/x15[2]} {-radix decimal} {/fft_test/x15[1]} {-radix decimal} {/fft_test/x15[0]} {-radix decimal}} /fft_test/x15
add wave -noupdate /fft_test/y0
add wave -noupdate /fft_test/y1
add wave -noupdate /fft_test/y2
add wave -noupdate /fft_test/y3
add wave -noupdate /fft_test/y4
add wave -noupdate /fft_test/y5
add wave -noupdate /fft_test/y6
add wave -noupdate /fft_test/y7
add wave -noupdate /fft_test/y8
add wave -noupdate /fft_test/y9
add wave -noupdate /fft_test/y10
add wave -noupdate /fft_test/y11
add wave -noupdate /fft_test/y12
add wave -noupdate /fft_test/y13
add wave -noupdate /fft_test/y14
add wave -noupdate /fft_test/y15
add wave -noupdate /fft_test/DUT/M
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {19 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {12 ns} {21 ns}
